spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false

postgres:
  server: localhost
  port: 5455
  database: dadjokes
  username: dad
  password: jokes

server:
  servlet:
    context-path: /dad
